### ISSUE TITLE
New Configuration/make Configuration editable in config.yml

### ISSUE THREAD

**Issue by TheButterbrotMan** [jackowldev/BlockyLife#1]
New Config:
Left interaction: +0.5
Jump: +1.0
Jump while sprinting: +2.0
Move: -0.025
Move < 80: -0.0005
Sprinting: +0.1
Still > 80: -1.25
Still < 80: -0.15
Still < 60: -0.05

**Comment by jackowldev** [comment]
WIP

**Comment by jackowldev** [comment]
Added
https://www.spigotmc.org/resources/blockylife-open-source-pulse-simulation.98151/download?version=430586
